export default function () {
  return {
    record: [
      {
        _id: "649b72c6f07badde0f32efb1",
        name: "64139fd4faf97152c2463280",
        record: [
          {
            kg: 20,
            rep: 12,
            break_time: 90,
            performance_time: 194,
            check: true,
          },
          {
            kg: 30,
            rep: 12,
            break_time: 90,
            performance_time: 86,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 85,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 73,
            check: true,
          },
          { kg: 40, rep: 8, break_time: 90, performance_time: 88, check: true },
        ],
        title: "바벨 데드리프트",
        date: 1687909062247,
      },
      {
        _id: "64522bdbcc7614d26c5b806a",
        name: "6413a00ffaf97152c2463283",
        record: [
          {
            kg: 20,
            rep: 12,
            break_time: 90,
            performance_time: 194,
            check: true,
          },
          {
            kg: 30,
            rep: 12,
            break_time: 90,
            performance_time: 86,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 85,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 73,
            check: true,
          },
          { kg: 40, rep: 8, break_time: 90, performance_time: 88, check: true },
        ],
        date: 1683106779572,
        title: "힙 어브덕션",
      },
      {
        _id: "645cb94c48086d0e1145ef55",
        name: "6413a00ffaf97152c2463283",
        record: [
          {
            kg: 20,
            rep: 12,
            break_time: 90,
            performance_time: 194,
            check: true,
          },
          {
            kg: 30,
            rep: 12,
            break_time: 90,
            performance_time: 86,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 85,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 73,
            check: true,
          },
          { kg: 40, rep: 8, break_time: 90, performance_time: 88, check: true },
        ],
        date: 1683798348369,
        title: "힙 어브덕션",
      },
      {
        _id: "6464bb9348086d0e1145f00a",
        name: "6413a00ffaf97152c2463283",
        record: [
          {
            kg: 20,
            rep: 12,
            break_time: 90,
            performance_time: 194,
            check: true,
          },
          {
            kg: 30,
            rep: 12,
            break_time: 90,
            performance_time: 86,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 85,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 73,
            check: true,
          },
          { kg: 40, rep: 8, break_time: 90, performance_time: 88, check: true },
        ],
        date: 1684323219750,
        title: "힙 어브덕션",
      },
      {
        _id: "646aa73148086d0e1145f071",
        name: "6413a00ffaf97152c2463283",
        record: [
          {
            kg: 20,
            rep: 12,
            break_time: 90,
            performance_time: 194,
            check: true,
          },
          {
            kg: 30,
            rep: 12,
            break_time: 90,
            performance_time: 86,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 85,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 73,
            check: true,
          },
          { kg: 40, rep: 8, break_time: 90, performance_time: 88, check: true },
        ],
        date: 1684711217949,
        title: "힙 어브덕션",
      },
      {
        _id: "647c7acceebbdeff6590afc4",
        name: "6413a00ffaf97152c2463283",
        record: [
          {
            kg: 20,
            rep: 12,
            break_time: 90,
            performance_time: 194,
            check: true,
          },
          {
            kg: 30,
            rep: 12,
            break_time: 90,
            performance_time: 86,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 85,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 73,
            check: true,
          },
          { kg: 40, rep: 8, break_time: 90, performance_time: 88, check: true },
        ],
        date: 1685879500576,
        title: "힙 어브덕션",
      },
      {
        _id: "6480020ceebbdeff6590affa",
        name: "6413a00ffaf97152c2463283",
        record: [
          {
            kg: 20,
            rep: 12,
            break_time: 90,
            performance_time: 194,
            check: true,
          },
          {
            kg: 30,
            rep: 12,
            break_time: 90,
            performance_time: 86,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 85,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 73,
            check: true,
          },
          { kg: 40, rep: 8, break_time: 90, performance_time: 88, check: true },
        ],
        date: 1686110732580,
        title: "힙 어브덕션",
      },
      {
        _id: "648871c79ff243d18be51c0e",
        name: "6413a00ffaf97152c2463283",
        record: [
          {
            kg: 20,
            rep: 12,
            break_time: 90,
            performance_time: 194,
            check: true,
          },
          {
            kg: 30,
            rep: 12,
            break_time: 90,
            performance_time: 86,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 85,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 73,
            check: true,
          },
          { kg: 40, rep: 8, break_time: 90, performance_time: 88, check: true },
        ],
        date: 1686663623975,
        title: "힙 어브덕션",
      },
      {
        _id: "649b72c6f07badde0f32efb2",
        name: "6413a00ffaf97152c2463283",
        record: [
          {
            kg: 20,
            rep: 12,
            break_time: 90,
            performance_time: 194,
            check: true,
          },
          {
            kg: 30,
            rep: 12,
            break_time: 90,
            performance_time: 86,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 85,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 73,
            check: true,
          },
          { kg: 40, rep: 8, break_time: 90, performance_time: 88, check: true },
        ],
        date: 1687909062247,
        title: "힙 어브덕션",
      },
      {
        _id: "64522bdbcc7614d26c5b806c",
        name: "6413a04afaf97152c2463285",
        record: [
          {
            kg: 20,
            rep: 12,
            break_time: 90,
            performance_time: 194,
            check: true,
          },
          {
            kg: 30,
            rep: 12,
            break_time: 90,
            performance_time: 86,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 85,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 73,
            check: true,
          },
          { kg: 40, rep: 8, break_time: 90, performance_time: 88, check: true },
        ],
        date: 1683106779572,
        title: "시티드 레그 컬",
      },
      {
        _id: "6464bb9348086d0e1145f00c",
        name: "6413a04afaf97152c2463285",
        record: [
          {
            kg: 20,
            rep: 12,
            break_time: 90,
            performance_time: 194,
            check: true,
          },
          {
            kg: 30,
            rep: 12,
            break_time: 90,
            performance_time: 86,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 85,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 73,
            check: true,
          },
          { kg: 40, rep: 8, break_time: 90, performance_time: 88, check: true },
        ],
        date: 1684323219750,
        title: "시티드 레그 컬",
      },
      {
        _id: "646aa73148086d0e1145f073",
        name: "6413a04afaf97152c2463285",
        record: [
          {
            kg: 20,
            rep: 12,
            break_time: 90,
            performance_time: 194,
            check: true,
          },
          {
            kg: 30,
            rep: 12,
            break_time: 90,
            performance_time: 86,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 85,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 73,
            check: true,
          },
          { kg: 40, rep: 8, break_time: 90, performance_time: 88, check: true },
        ],
        date: 1684711217949,
        title: "시티드 레그 컬",
      },
      {
        _id: "648871c79ff243d18be51c10",
        name: "6413a04afaf97152c2463285",
        record: [
          {
            kg: 20,
            rep: 12,
            break_time: 90,
            performance_time: 194,
            check: true,
          },
          {
            kg: 30,
            rep: 12,
            break_time: 90,
            performance_time: 86,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 85,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 73,
            check: true,
          },
          { kg: 40, rep: 8, break_time: 90, performance_time: 88, check: true },
        ],
        date: 1686663623975,
        title: "시티드 레그 컬",
      },
      {
        _id: "649b72c6f07badde0f32efb3",
        name: "6413a04afaf97152c2463285",
        record: [
          {
            kg: 20,
            rep: 12,
            break_time: 90,
            performance_time: 194,
            check: true,
          },
          {
            kg: 30,
            rep: 12,
            break_time: 90,
            performance_time: 86,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 85,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 73,
            check: true,
          },
          { kg: 40, rep: 8, break_time: 90, performance_time: 88, check: true },
        ],
        date: 1687909062247,
        title: "시티드 레그 컬",
      },
      {
        _id: "6450dddea15c208e8e0c41a0",
        name: "64139e728807716d76da8376",
        record: [
          {
            kg: 20,
            rep: 12,
            break_time: 90,
            performance_time: 194,
            check: true,
          },
          {
            kg: 30,
            rep: 12,
            break_time: 90,
            performance_time: 86,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 85,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 73,
            check: true,
          },
          { kg: 40, rep: 8, break_time: 90, performance_time: 88, check: true },
        ],
        date: 1683021278414,
        title: "풀 업",
      },
      {
        _id: "6458c63448086d0e1145ee06",
        name: "64139e728807716d76da8376",
        record: [
          {
            kg: 20,
            rep: 12,
            break_time: 90,
            performance_time: 194,
            check: true,
          },
          {
            kg: 30,
            rep: 12,
            break_time: 90,
            performance_time: 86,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 85,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 73,
            check: true,
          },
          { kg: 40, rep: 8, break_time: 90, performance_time: 88, check: true },
        ],
        date: 1683539508507,
        title: "풀 업",
      },
      {
        _id: "6467642448086d0e1145f047",
        name: "64139e728807716d76da8376",
        record: [
          {
            kg: 20,
            rep: 12,
            break_time: 90,
            performance_time: 194,
            check: true,
          },
          {
            kg: 30,
            rep: 12,
            break_time: 90,
            performance_time: 86,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 85,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 73,
            check: true,
          },
          { kg: 40, rep: 8, break_time: 90, performance_time: 88, check: true },
        ],
        date: 1684497444630,
        title: "풀 업",
      },
      {
        _id: "6479a889eebbdeff6590afbe",
        name: "64139e728807716d76da8376",
        record: [
          {
            kg: 20,
            rep: 12,
            break_time: 90,
            performance_time: 194,
            check: true,
          },
          {
            kg: 30,
            rep: 12,
            break_time: 90,
            performance_time: 86,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 85,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 73,
            check: true,
          },
          { kg: 40, rep: 8, break_time: 90, performance_time: 88, check: true },
        ],
        date: 1685694601495,
        title: "풀 업",
      },
      {
        _id: "6486cd2aeebbdeff6590b06b",
        name: "64139e728807716d76da8376",
        record: [
          {
            kg: 20,
            rep: 12,
            break_time: 90,
            performance_time: 194,
            check: true,
          },
          {
            kg: 30,
            rep: 12,
            break_time: 90,
            performance_time: 86,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 85,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 73,
            check: true,
          },
          { kg: 40, rep: 8, break_time: 90, performance_time: 88, check: true },
        ],
        date: 1686555946651,
        title: "풀 업",
      },
      {
        _id: "649b72c6f07badde0f32efad",
        name: "64139e728807716d76da8376",
        record: [
          {
            kg: 20,
            rep: 12,
            break_time: 90,
            performance_time: 194,
            check: true,
          },
          {
            kg: 30,
            rep: 12,
            break_time: 90,
            performance_time: 86,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 85,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 73,
            check: true,
          },
          { kg: 40, rep: 8, break_time: 90, performance_time: 88, check: true },
        ],
        date: 1687909062247,
        title: "풀 업",
      },
      {
        _id: "6450dddea15c208e8e0c419f",
        name: "64139529e90ddbd84773f8ba",
        record: [
          {
            kg: 20,
            rep: 12,
            break_time: 90,
            performance_time: 194,
            check: true,
          },
          {
            kg: 30,
            rep: 12,
            break_time: 90,
            performance_time: 86,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 85,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 73,
            check: true,
          },
          { kg: 40, rep: 8, break_time: 90, performance_time: 88, check: true },
        ],
        date: 1683021278414,
        title: "핀 로드 랫 풀 다운",
      },
      {
        _id: "6458c63448086d0e1145ee05",
        name: "64139529e90ddbd84773f8ba",
        record: [
          {
            kg: 20,
            rep: 12,
            break_time: 90,
            performance_time: 194,
            check: true,
          },
          {
            kg: 30,
            rep: 12,
            break_time: 90,
            performance_time: 86,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 85,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 73,
            check: true,
          },
          { kg: 40, rep: 8, break_time: 90, performance_time: 88, check: true },
        ],
        date: 1683539508507,
        title: "핀 로드 랫 풀 다운",
      },
      {
        _id: "6463983248086d0e1145efeb",
        name: "64139529e90ddbd84773f8ba",
        record: [
          {
            kg: 20,
            rep: 12,
            break_time: 90,
            performance_time: 194,
            check: true,
          },
          {
            kg: 30,
            rep: 12,
            break_time: 90,
            performance_time: 86,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 85,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 73,
            check: true,
          },
          { kg: 40, rep: 8, break_time: 90, performance_time: 88, check: true },
        ],
        date: 1684248626889,
        title: "핀 로드 랫 풀 다운",
      },
      {
        _id: "6467642448086d0e1145f046",
        name: "64139529e90ddbd84773f8ba",
        record: [
          {
            kg: 20,
            rep: 12,
            break_time: 90,
            performance_time: 194,
            check: true,
          },
          {
            kg: 30,
            rep: 12,
            break_time: 90,
            performance_time: 86,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 85,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 73,
            check: true,
          },
          { kg: 40, rep: 8, break_time: 90, performance_time: 88, check: true },
        ],
        date: 1684497444630,
        title: "핀 로드 랫 풀 다운",
      },
      {
        _id: "6479a889eebbdeff6590afbd",
        name: "64139529e90ddbd84773f8ba",
        record: [
          {
            kg: 20,
            rep: 12,
            break_time: 90,
            performance_time: 194,
            check: true,
          },
          {
            kg: 30,
            rep: 12,
            break_time: 90,
            performance_time: 86,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 85,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 73,
            check: true,
          },
          { kg: 40, rep: 8, break_time: 90, performance_time: 88, check: true },
        ],
        date: 1685694601495,
        title: "핀 로드 랫 풀 다운",
      },
      {
        _id: "647f1b9ceebbdeff6590aff4",
        name: "64139529e90ddbd84773f8ba",
        record: [
          {
            kg: 20,
            rep: 12,
            break_time: 90,
            performance_time: 194,
            check: true,
          },
          {
            kg: 30,
            rep: 12,
            break_time: 90,
            performance_time: 86,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 85,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 73,
            check: true,
          },
          { kg: 40, rep: 8, break_time: 90, performance_time: 88, check: true },
        ],
        date: 1686051740553,
        title: "핀 로드 랫 풀 다운",
      },
      {
        _id: "6486cd2aeebbdeff6590b06a",
        name: "64139529e90ddbd84773f8ba",
        record: [
          {
            kg: 20,
            rep: 12,
            break_time: 90,
            performance_time: 194,
            check: true,
          },
          {
            kg: 30,
            rep: 12,
            break_time: 90,
            performance_time: 86,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 85,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 73,
            check: true,
          },
          { kg: 40, rep: 8, break_time: 90, performance_time: 88, check: true },
        ],
        date: 1686555946651,
        title: "핀 로드 랫 풀 다운",
      },
      {
        _id: "649b72c6f07badde0f32efae",
        name: "64139529e90ddbd84773f8ba",
        record: [
          {
            kg: 20,
            rep: 12,
            break_time: 90,
            performance_time: 194,
            check: true,
          },
          {
            kg: 30,
            rep: 12,
            break_time: 90,
            performance_time: 86,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 85,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 73,
            check: true,
          },
          { kg: 40, rep: 8, break_time: 90, performance_time: 88, check: true },
        ],
        date: 1687909062247,
        title: "핀 로드 랫 풀 다운",
      },
      {
        _id: "6450dddea15c208e8e0c41a1",
        name: "641394fde90ddbd84773f8b9",
        record: [
          {
            kg: 20,
            rep: 12,
            break_time: 90,
            performance_time: 194,
            check: true,
          },
          {
            kg: 30,
            rep: 12,
            break_time: 90,
            performance_time: 86,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 85,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 73,
            check: true,
          },
          { kg: 40, rep: 8, break_time: 90, performance_time: 88, check: true },
        ],
        date: 1683021278414,
        title: "케이블 원 암 시티드 로우",
      },
      {
        _id: "6458c63448086d0e1145ee07",
        name: "641394fde90ddbd84773f8b9",
        record: [
          {
            kg: 20,
            rep: 12,
            break_time: 90,
            performance_time: 194,
            check: true,
          },
          {
            kg: 30,
            rep: 12,
            break_time: 90,
            performance_time: 86,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 85,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 73,
            check: true,
          },
          { kg: 40, rep: 8, break_time: 90, performance_time: 88, check: true },
        ],
        date: 1683539508507,
        title: "케이블 원 암 시티드 로우",
      },
      {
        _id: "6467642448086d0e1145f048",
        name: "641394fde90ddbd84773f8b9",
        record: [
          {
            kg: 20,
            rep: 12,
            break_time: 90,
            performance_time: 194,
            check: true,
          },
          {
            kg: 30,
            rep: 12,
            break_time: 90,
            performance_time: 86,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 85,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 73,
            check: true,
          },
          { kg: 40, rep: 8, break_time: 90, performance_time: 88, check: true },
        ],
        date: 1684497444630,
        title: "케이블 원 암 시티드 로우",
      },
      {
        _id: "6479a889eebbdeff6590afbf",
        name: "641394fde90ddbd84773f8b9",
        record: [
          {
            kg: 20,
            rep: 12,
            break_time: 90,
            performance_time: 194,
            check: true,
          },
          {
            kg: 30,
            rep: 12,
            break_time: 90,
            performance_time: 86,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 85,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 73,
            check: true,
          },
          { kg: 40, rep: 8, break_time: 90, performance_time: 88, check: true },
        ],
        date: 1685694601495,
        title: "케이블 원 암 시티드 로우",
      },
      {
        _id: "6450dddea15c208e8e0c41a2",
        name: "64139c4f8807716d76da8374",
        record: [
          {
            kg: 20,
            rep: 12,
            break_time: 90,
            performance_time: 194,
            check: true,
          },
          {
            kg: 30,
            rep: 12,
            break_time: 90,
            performance_time: 86,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 85,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 73,
            check: true,
          },
          { kg: 40, rep: 8, break_time: 90, performance_time: 88, check: true },
        ],
        date: 1683021278414,
        title: "핀 로드 리버스 팩 덱 플라이",
      },
      {
        _id: "6458c63448086d0e1145ee08",
        name: "64139c4f8807716d76da8374",
        record: [
          {
            kg: 20,
            rep: 12,
            break_time: 90,
            performance_time: 194,
            check: true,
          },
          {
            kg: 30,
            rep: 12,
            break_time: 90,
            performance_time: 86,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 85,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 73,
            check: true,
          },
          { kg: 40, rep: 8, break_time: 90, performance_time: 88, check: true },
        ],
        date: 1683539508507,
        title: "핀 로드 리버스 팩 덱 플라이",
      },
      {
        _id: "6467642448086d0e1145f049",
        name: "64139c4f8807716d76da8374",
        record: [
          {
            kg: 20,
            rep: 12,
            break_time: 90,
            performance_time: 194,
            check: true,
          },
          {
            kg: 30,
            rep: 12,
            break_time: 90,
            performance_time: 86,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 85,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 73,
            check: true,
          },
          { kg: 40, rep: 8, break_time: 90, performance_time: 88, check: true },
        ],
        date: 1684497444630,
        title: "핀 로드 리버스 팩 덱 플라이",
      },
      {
        _id: "6479a889eebbdeff6590afc0",
        name: "64139c4f8807716d76da8374",
        record: [
          {
            kg: 20,
            rep: 12,
            break_time: 90,
            performance_time: 194,
            check: true,
          },
          {
            kg: 30,
            rep: 12,
            break_time: 90,
            performance_time: 86,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 85,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 73,
            check: true,
          },
          { kg: 40, rep: 8, break_time: 90, performance_time: 88, check: true },
        ],
        date: 1685694601495,
        title: "핀 로드 리버스 팩 덱 플라이",
      },
      {
        _id: "647f1b9ceebbdeff6590aff6",
        name: "64139c4f8807716d76da8374",
        record: [
          {
            kg: 20,
            rep: 12,
            break_time: 90,
            performance_time: 194,
            check: true,
          },
          {
            kg: 30,
            rep: 12,
            break_time: 90,
            performance_time: 86,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 85,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 73,
            check: true,
          },
          { kg: 40, rep: 8, break_time: 90, performance_time: 88, check: true },
        ],
        date: 1686051740553,
        title: "핀 로드 리버스 팩 덱 플라이",
      },
      {
        _id: "6486cd2aeebbdeff6590b06c",
        name: "64139c4f8807716d76da8374",
        record: [
          {
            kg: 20,
            rep: 12,
            break_time: 90,
            performance_time: 194,
            check: true,
          },
          {
            kg: 30,
            rep: 12,
            break_time: 90,
            performance_time: 86,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 85,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 73,
            check: true,
          },
          { kg: 40, rep: 8, break_time: 90, performance_time: 88, check: true },
        ],
        date: 1686555946651,
        title: "핀 로드 리버스 팩 덱 플라이",
      },
      {
        _id: "649b72c6f07badde0f32efb0",
        name: "64139c4f8807716d76da8374",
        record: [
          {
            kg: 20,
            rep: 12,
            break_time: 90,
            performance_time: 194,
            check: true,
          },
          {
            kg: 30,
            rep: 12,
            break_time: 90,
            performance_time: 86,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 85,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 73,
            check: true,
          },
          { kg: 40, rep: 8, break_time: 90, performance_time: 88, check: true },
        ],
        date: 1687909062247,
        title: "핀 로드 리버스 팩 덱 플라이",
      },
      {
        _id: "64522bdbcc7614d26c5b8068",
        name: "64139fdbfaf97152c2463281",
        record: [
          {
            kg: 20,
            rep: 12,
            break_time: 90,
            performance_time: 194,
            check: true,
          },
          {
            kg: 30,
            rep: 12,
            break_time: 90,
            performance_time: 86,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 85,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 73,
            check: true,
          },
          { kg: 40, rep: 8, break_time: 90, performance_time: 88, check: true },
        ],
        date: 1683106779572,
        title: "바벨 스쿼트",
      },
      {
        _id: "645cb94c48086d0e1145ef53",
        name: "64139fdbfaf97152c2463281",
        record: [
          {
            kg: 20,
            rep: 12,
            break_time: 90,
            performance_time: 194,
            check: true,
          },
          {
            kg: 30,
            rep: 12,
            break_time: 90,
            performance_time: 86,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 85,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 73,
            check: true,
          },
          { kg: 40, rep: 8, break_time: 90, performance_time: 88, check: true },
        ],
        date: 1683798348369,
        title: "바벨 스쿼트",
      },
      {
        _id: "6464bb9348086d0e1145f008",
        name: "64139fdbfaf97152c2463281",
        record: [
          {
            kg: 20,
            rep: 12,
            break_time: 90,
            performance_time: 194,
            check: true,
          },
          {
            kg: 30,
            rep: 12,
            break_time: 90,
            performance_time: 86,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 85,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 73,
            check: true,
          },
          { kg: 40, rep: 8, break_time: 90, performance_time: 88, check: true },
        ],
        date: 1684323219750,
        title: "바벨 스쿼트",
      },
      {
        _id: "646aa73148086d0e1145f06f",
        name: "64139fdbfaf97152c2463281",
        record: [
          {
            kg: 20,
            rep: 12,
            break_time: 90,
            performance_time: 194,
            check: true,
          },
          {
            kg: 30,
            rep: 12,
            break_time: 90,
            performance_time: 86,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 85,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 73,
            check: true,
          },
          { kg: 40, rep: 8, break_time: 90, performance_time: 88, check: true },
        ],
        date: 1684711217949,
        title: "바벨 스쿼트",
      },
      {
        _id: "647c7acceebbdeff6590afc2",
        name: "64139fdbfaf97152c2463281",
        record: [
          {
            kg: 20,
            rep: 12,
            break_time: 90,
            performance_time: 194,
            check: true,
          },
          {
            kg: 30,
            rep: 12,
            break_time: 90,
            performance_time: 86,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 85,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 73,
            check: true,
          },
          { kg: 40, rep: 8, break_time: 90, performance_time: 88, check: true },
        ],
        date: 1685879500576,
        title: "바벨 스쿼트",
      },
      {
        _id: "6480020ceebbdeff6590aff8",
        name: "64139fdbfaf97152c2463281",
        record: [
          {
            kg: 20,
            rep: 12,
            break_time: 90,
            performance_time: 194,
            check: true,
          },
          {
            kg: 30,
            rep: 12,
            break_time: 90,
            performance_time: 86,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 85,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 73,
            check: true,
          },
          { kg: 40, rep: 8, break_time: 90, performance_time: 88, check: true },
        ],
        date: 1686110732580,
        title: "바벨 스쿼트",
      },
      {
        _id: "648871c79ff243d18be51c0c",
        name: "64139fdbfaf97152c2463281",
        record: [
          {
            kg: 20,
            rep: 12,
            break_time: 90,
            performance_time: 194,
            check: true,
          },
          {
            kg: 30,
            rep: 12,
            break_time: 90,
            performance_time: 86,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 85,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 73,
            check: true,
          },
          { kg: 40, rep: 8, break_time: 90, performance_time: 88, check: true },
        ],
        date: 1686663623975,
        title: "바벨 스쿼트",
      },
      {
        _id: "649d8afdf07badde0f32efbb",
        name: "64139fdbfaf97152c2463281",
        record: [
          {
            kg: 20,
            rep: 12,
            break_time: 90,
            performance_time: 194,
            check: true,
          },
          {
            kg: 30,
            rep: 12,
            break_time: 90,
            performance_time: 86,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 85,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 73,
            check: true,
          },
          { kg: 40, rep: 8, break_time: 90, performance_time: 88, check: true },
        ],
        date: 1688046333261,
        title: "바벨 스쿼트",
      },
      {
        _id: "64522bdbcc7614d26c5b8069",
        name: "6413a001faf97152c2463282",
        record: [
          {
            kg: 20,
            rep: 12,
            break_time: 90,
            performance_time: 194,
            check: true,
          },
          {
            kg: 30,
            rep: 12,
            break_time: 90,
            performance_time: 86,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 85,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 73,
            check: true,
          },
          { kg: 40, rep: 8, break_time: 90, performance_time: 88, check: true },
        ],
        date: 1683106779572,
        title: "힙 어덕션",
      },
      {
        _id: "645cb94c48086d0e1145ef54",
        name: "6413a001faf97152c2463282",
        record: [
          {
            kg: 20,
            rep: 12,
            break_time: 90,
            performance_time: 194,
            check: true,
          },
          {
            kg: 30,
            rep: 12,
            break_time: 90,
            performance_time: 86,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 85,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 73,
            check: true,
          },
          { kg: 40, rep: 8, break_time: 90, performance_time: 88, check: true },
        ],
        date: 1683798348369,
        title: "힙 어덕션",
      },
      {
        _id: "6464bb9348086d0e1145f009",
        name: "6413a001faf97152c2463282",
        record: [
          {
            kg: 20,
            rep: 12,
            break_time: 90,
            performance_time: 194,
            check: true,
          },
          {
            kg: 30,
            rep: 12,
            break_time: 90,
            performance_time: 86,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 85,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 73,
            check: true,
          },
          { kg: 40, rep: 8, break_time: 90, performance_time: 88, check: true },
        ],
        date: 1684323219750,
        title: "힙 어덕션",
      },
      {
        _id: "646aa73148086d0e1145f070",
        name: "6413a001faf97152c2463282",
        record: [
          {
            kg: 20,
            rep: 12,
            break_time: 90,
            performance_time: 194,
            check: true,
          },
          {
            kg: 30,
            rep: 12,
            break_time: 90,
            performance_time: 86,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 85,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 73,
            check: true,
          },
          { kg: 40, rep: 8, break_time: 90, performance_time: 88, check: true },
        ],
        date: 1684711217949,
        title: "힙 어덕션",
      },
      {
        _id: "647c7acceebbdeff6590afc3",
        name: "6413a001faf97152c2463282",
        record: [
          {
            kg: 20,
            rep: 12,
            break_time: 90,
            performance_time: 194,
            check: true,
          },
          {
            kg: 30,
            rep: 12,
            break_time: 90,
            performance_time: 86,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 85,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 73,
            check: true,
          },
          { kg: 40, rep: 8, break_time: 90, performance_time: 88, check: true },
        ],
        date: 1685879500576,
        title: "힙 어덕션",
      },
      {
        _id: "6480020ceebbdeff6590aff9",
        name: "6413a001faf97152c2463282",
        record: [
          {
            kg: 20,
            rep: 12,
            break_time: 90,
            performance_time: 194,
            check: true,
          },
          {
            kg: 30,
            rep: 12,
            break_time: 90,
            performance_time: 86,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 85,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 73,
            check: true,
          },
          { kg: 40, rep: 8, break_time: 90, performance_time: 88, check: true },
        ],
        date: 1686110732580,
        title: "힙 어덕션",
      },
      {
        _id: "648871c79ff243d18be51c0d",
        name: "6413a001faf97152c2463282",
        record: [
          {
            kg: 20,
            rep: 12,
            break_time: 90,
            performance_time: 194,
            check: true,
          },
          {
            kg: 30,
            rep: 12,
            break_time: 90,
            performance_time: 86,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 85,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 73,
            check: true,
          },
          { kg: 40, rep: 8, break_time: 90, performance_time: 88, check: true },
        ],
        date: 1686663623975,
        title: "힙 어덕션",
      },
      {
        _id: "649d8afdf07badde0f32efbc",
        name: "6413a001faf97152c2463282",
        record: [
          {
            kg: 20,
            rep: 12,
            break_time: 90,
            performance_time: 194,
            check: true,
          },
          {
            kg: 30,
            rep: 12,
            break_time: 90,
            performance_time: 86,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 85,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 73,
            check: true,
          },
          { kg: 40, rep: 8, break_time: 90, performance_time: 88, check: true },
        ],
        date: 1688046333261,
        title: "힙 어덕션",
      },
      {
        _id: "64522bdbcc7614d26c5b806b",
        name: "6413a041faf97152c2463284",
        record: [
          {
            kg: 20,
            rep: 12,
            break_time: 90,
            performance_time: 194,
            check: true,
          },
          {
            kg: 30,
            rep: 12,
            break_time: 90,
            performance_time: 86,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 85,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 73,
            check: true,
          },
          { kg: 40, rep: 8, break_time: 90, performance_time: 88, check: true },
        ],
        date: 1683106779572,
        title: "레그 익스텐션",
      },
      {
        _id: "6464bb9348086d0e1145f00b",
        name: "6413a041faf97152c2463284",
        record: [
          {
            kg: 20,
            rep: 12,
            break_time: 90,
            performance_time: 194,
            check: true,
          },
          {
            kg: 30,
            rep: 12,
            break_time: 90,
            performance_time: 86,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 85,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 73,
            check: true,
          },
          { kg: 40, rep: 8, break_time: 90, performance_time: 88, check: true },
        ],
        date: 1684323219750,
        title: "레그 익스텐션",
      },
      {
        _id: "646aa73148086d0e1145f072",
        name: "6413a041faf97152c2463284",
        record: [
          {
            kg: 20,
            rep: 12,
            break_time: 90,
            performance_time: 194,
            check: true,
          },
          {
            kg: 30,
            rep: 12,
            break_time: 90,
            performance_time: 86,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 85,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 73,
            check: true,
          },
          { kg: 40, rep: 8, break_time: 90, performance_time: 88, check: true },
        ],
        date: 1684711217949,
        title: "레그 익스텐션",
      },
      {
        _id: "6480020ceebbdeff6590affb",
        name: "6413a041faf97152c2463284",
        record: [
          {
            kg: 20,
            rep: 12,
            break_time: 90,
            performance_time: 194,
            check: true,
          },
          {
            kg: 30,
            rep: 12,
            break_time: 90,
            performance_time: 86,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 85,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 73,
            check: true,
          },
          { kg: 40, rep: 8, break_time: 90, performance_time: 88, check: true },
        ],
        date: 1686110732580,
        title: "레그 익스텐션",
      },
      {
        _id: "648871c79ff243d18be51c0f",
        name: "6413a041faf97152c2463284",
        record: [
          {
            kg: 20,
            rep: 12,
            break_time: 90,
            performance_time: 194,
            check: true,
          },
          {
            kg: 30,
            rep: 12,
            break_time: 90,
            performance_time: 86,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 85,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 73,
            check: true,
          },
          { kg: 40, rep: 8, break_time: 90, performance_time: 88, check: true },
        ],
        date: 1686663623975,
        title: "레그 익스텐션",
      },
      {
        _id: "649d8afdf07badde0f32efbd",
        name: "6413a041faf97152c2463284",
        record: [
          {
            kg: 20,
            rep: 12,
            break_time: 90,
            performance_time: 194,
            check: true,
          },
          {
            kg: 30,
            rep: 12,
            break_time: 90,
            performance_time: 86,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 85,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 73,
            check: true,
          },
          { kg: 40, rep: 8, break_time: 90, performance_time: 88, check: true },
        ],
        date: 1688046333261,
        title: "레그 익스텐션",
      },
      {
        _id: "644f6908a15c208e8e0c4197",
        name: "64127064ce2d358a242dd925",
        record: [
          {
            kg: 20,
            rep: 12,
            break_time: 90,
            performance_time: 194,
            check: true,
          },
          {
            kg: 30,
            rep: 12,
            break_time: 90,
            performance_time: 86,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 85,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 73,
            check: true,
          },
          { kg: 40, rep: 8, break_time: 90, performance_time: 88, check: true },
        ],
        date: 1682925832587,
        title: "바벨 플랫 벤치 프레스",
      },
      {
        _id: "6460ba6d48086d0e1145efe2",
        name: "64127064ce2d358a242dd925",
        record: [
          {
            kg: 20,
            rep: 12,
            break_time: 90,
            performance_time: 194,
            check: true,
          },
          {
            kg: 30,
            rep: 12,
            break_time: 90,
            performance_time: 86,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 85,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 73,
            check: true,
          },
          { kg: 40, rep: 8, break_time: 90, performance_time: 88, check: true },
        ],
        date: 1684060781215,
        title: "바벨 플랫 벤치 프레스",
      },
      {
        _id: "64774393eebbdeff6590afb8",
        name: "64127064ce2d358a242dd925",
        record: [
          {
            kg: 20,
            rep: 12,
            break_time: 90,
            performance_time: 194,
            check: true,
          },
          {
            kg: 30,
            rep: 12,
            break_time: 90,
            performance_time: 86,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 85,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 73,
            check: true,
          },
          { kg: 40, rep: 8, break_time: 90, performance_time: 88, check: true },
        ],
        date: 1685537683552,
        title: "바벨 플랫 벤치 프레스",
      },
      {
        _id: "647dd968eebbdeff6590afeb",
        name: "64127064ce2d358a242dd925",
        record: [
          {
            kg: 20,
            rep: 12,
            break_time: 90,
            performance_time: 194,
            check: true,
          },
          {
            kg: 30,
            rep: 12,
            break_time: 90,
            performance_time: 86,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 85,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 73,
            check: true,
          },
          { kg: 40, rep: 8, break_time: 90, performance_time: 88, check: true },
        ],
        date: 1685969256250,
        title: "바벨 플랫 벤치 프레스",
      },
      {
        _id: "6481b334eebbdeff6590b039",
        name: "64127064ce2d358a242dd925",
        record: [
          {
            kg: 20,
            rep: 12,
            break_time: 90,
            performance_time: 194,
            check: true,
          },
          {
            kg: 30,
            rep: 12,
            break_time: 90,
            performance_time: 86,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 85,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 73,
            check: true,
          },
          { kg: 40, rep: 8, break_time: 90, performance_time: 88, check: true },
        ],
        date: 1686221620820,
        title: "바벨 플랫 벤치 프레스",
      },
      {
        _id: "648fd52f9ff243d18be51c31",
        name: "64127064ce2d358a242dd925",
        record: [
          {
            kg: 20,
            rep: 12,
            break_time: 90,
            performance_time: 194,
            check: true,
          },
          {
            kg: 30,
            rep: 12,
            break_time: 90,
            performance_time: 86,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 85,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 73,
            check: true,
          },
          { kg: 40, rep: 8, break_time: 90, performance_time: 88, check: true },
        ],
        date: 1687147823671,
        title: "바벨 플랫 벤치 프레스",
      },
      {
        _id: "649d8afdf07badde0f32efbe",
        name: "64127064ce2d358a242dd925",
        record: [
          {
            kg: 20,
            rep: 12,
            break_time: 90,
            performance_time: 194,
            check: true,
          },
          {
            kg: 30,
            rep: 12,
            break_time: 90,
            performance_time: 86,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 85,
            check: true,
          },
          {
            kg: 40,
            rep: 10,
            break_time: 90,
            performance_time: 73,
            check: true,
          },
          { kg: 40, rep: 8, break_time: 90, performance_time: 88, check: true },
        ],
        date: 1688046333261,
        title: "바벨 플랫 벤치 프레스",
      },
    ],
  };
}
